# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-07-31 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_users_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='experience',
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='experience',
            field=models.FloatField(blank=True, null=True, verbose_name='\u041e\u043f\u044b\u0442'),
        ),
    ]
