# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-08-01 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20180731_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lat',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='lng',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='servicemaster',
            name='lat',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='servicemaster',
            name='lng',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
    ]
