# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-08-04 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20180802_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
