# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-08-08 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20180804_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
