# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-08-08 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_order_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemaster',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
    ]
