# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-08-09 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20180809_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='servicemaster',
            old_name='user',
            new_name='users',
        ),
    ]
