# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-08-09 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20180809_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='users',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='users',
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.Users', verbose_name='\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.Category', verbose_name='\u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicemaster',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.Category', verbose_name='\u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
            preserve_default=False,
        ),
    ]
