# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-08-14 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20180814_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forum',
            options={'verbose_name': '\u0424\u043e\u0440\u0443\u043c', 'verbose_name_plural': '\u0424\u043e\u0440\u0443\u043c'},
        ),
    ]
