# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-08-16 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_auto_20180814_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='device_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='device id'),
        ),
    ]
