# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-10-22 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_auto_20181016_0205'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmationService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, default=1, null=True)),
                ('confirmation', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.ServiceMaster', verbose_name='\u0417\u0430\u043a\u0430\u0437')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Users', verbose_name='\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
        ),
        migrations.AddField(
            model_name='confirmationorder',
            name='status',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
