# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-11-23 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0022_auto_20181022_0617'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u043a\u043e\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Users', verbose_name='\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='\u043e\u0446\u0435\u043d\u043a\u0430')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Users', verbose_name='\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=post.models.image_upload_to, verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u04301'),
        ),
        migrations.AddField(
            model_name='order',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=post.models.image_upload_to, verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u04302'),
        ),
        migrations.AddField(
            model_name='order',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=post.models.image_upload_to, verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u04303'),
        ),
        migrations.AddField(
            model_name='order',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=post.models.image_upload_to, verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u04304'),
        ),
        migrations.AddField(
            model_name='order',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to=post.models.image_upload_to, verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u04305'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=post.models.image_upload_to, verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u04301'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=post.models.image_upload_to, verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u04302'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=post.models.image_upload_to, verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u04303'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=post.models.image_upload_to, verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u04304'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to=post.models.image_upload_to, verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u04305'),
        ),
    ]
