# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-02-18 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0024_auto_20190116_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.IntegerField(blank=True, null=True)),
                ('service', models.IntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u041a\u043e\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u041a\u043e\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439',
                'verbose_name_plural': '\u041a\u043e\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='CommentService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.IntegerField(blank=True, null=True)),
                ('service', models.IntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u041a\u043e\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u041a\u043e\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439',
                'verbose_name_plural': '\u041a\u043e\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0438',
            },
        ),
        migrations.AddField(
            model_name='forum',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=post.models.image_upload_to, verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u04301'),
        ),
        migrations.AddField(
            model_name='forum',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=post.models.image_upload_to, verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u04302'),
        ),
        migrations.AddField(
            model_name='forum',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=post.models.image_upload_to, verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u04303'),
        ),
        migrations.AddField(
            model_name='forum',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=post.models.image_upload_to, verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u04304'),
        ),
        migrations.AddField(
            model_name='forum',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to=post.models.image_upload_to, verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u04305'),
        ),
        migrations.AddField(
            model_name='order',
            name='info',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='\u0434\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u0430\u044f \u0438\u043d\u0444\u043e\u0440\u043c\u0444\u0446\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='info',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='\u0434\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u0430\u044f \u0438\u043d\u0444\u043e\u0440\u043c\u0444\u0446\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='servicemaster',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
    ]
