# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-02-18 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0025_auto_20190218_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentorder',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='commentservice',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
